server:
  port: 8080

spring:
  main:
    banner-mode: console
  jpa:
    database: H2
    hibernate:
      ddl-auto: none # DB\uB97C \uCD08\uAE30\uD654\uD558\uB294 \uC18D\uC131
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true
      sort:
        sort-parameter: sort
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8