# Students 등록 ( Default )
POST http://127.0.0.1:8080/students/default
Content-Type: application/json

{
  "id": 1,
  "name": "123123",
  "email": "simpolor@gmail.com",
  "grade": 2,
  "age": 18,
  "hobbies": ["축구"],
  "classroom": "SUN"
}

###

# Students 등록 ( Custom )
POST http://127.0.0.1:8080/students/custom
Content-Type: application/json

{
  "id": 1,
  "email": "simpolor@gmail.com",
  "grade": 2,
  "age": 18,
  "hobbies": ["축구"],
  "classroom": "FLOWER"
}

###

# Students 등록 ( Bad request )
POST http://127.0.0.1:8080/students/bad-request
Content-Type: application/json

{
  "id": 1,
  "email": "simpolor@gmail.com",
  "grade": 2,
  "age": 18,
  "hobbies": ["축구"],
  "classroom": "FLOWER"
}

###

# Students 등록 ( Factory )
POST http://127.0.0.1:8080/students/factory
Content-Type: application/json

{
  "id": 1,
  "email": "simpolor@gmail.com",
  "grade": 2,
  "age": 18,
  "hobbies": ["축구"],
  "classroom": "FLOWER"
}

###