server:
  port: 8080

spring:
  main:
    banner-mode: console
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: true
      sort:
        sort-parameter: sort