server:
  port: 8080

spring:
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 200
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: size
        #sort:
        #sort-parameter: seq
  jpa:
    database: H2
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console