# Student 리스트
GET http://127.0.0.1:8080/line/students

###

# Student 조회
GET http://127.0.0.1:8080/line/students/1

###

# Student 등록
POST http://127.0.0.1:8080/line/students
Content-Type: application/json

{
  "name": "박석영",
  "grade": 2,
  "age": 18,
  "hobbies": ["축구"]
}

###