server:
  port: 8080

spring:
  main:
    banner-mode: console
  messages:
    basename: messages/message
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8


application:
  serverInfo:
    baseUrl: localhost:8080

jsf:
  primefaces:
    FONT_AWESOME: true

logging:
  level:
    org.thymeleaf: DEBUG
