server:
  port: 8080
  servlet:
    context-path: /student

spring:
  main:
    banner-mode: console
  messages:
    basename: messages/message
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

jsf:
  primefaces:
    FONT_AWESOME: true

