server:
  port: 8080

application:
  remote:
    url: http://localhost:8080

#feign:
#  client:
#    config:
#      defaut: #{feignName}
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic


#feign:
#  client:
#    config:
#      feignName: # @FeignClient?? name ?, ???? ????? default
#        connectTimeout: 5000 # hystrix? timeout ??? ? ???, hystirx ??? ???
#        readTimeout: 5000
#        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer # ??? ???? ? ???? ?? ??
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
#          - com.example.BarRequestInterceptor
#        decode404: false
#        encoder: com.example.SimpleEncoder # body? ??? Object? ???? class ??, ??
#        decoder: com.example.SimpleDecoder
#        contract: com.example.SimpleContract

# loggerLevel : NONE, BASIC, HEADER, FULL? ??? ? ??
#  - NONE : default, ??? ??? ??
#  - BASIC : Request Method, URL? ?? ??, ?? ??? ??
#  - HEADERS : BASIC? ??? ????, ??, ??? ??? ??
#  - FULL : ??, ??? header, body, metadata? ??
#  - logging.level.com.example.demo.PostClient: debug ?? debug logger ??? ?? ????